/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenii_andreamendoza;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        TimeThread t = new TimeThread(Time);
        Thread t2 = new Thread(t);
        t2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Whatever = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Time = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Depositos = new javax.swing.JDialog();
        CPropia = new javax.swing.JRadioButton();
        CAjena = new javax.swing.JRadioButton();
        Cuentas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        C100_2 = new javax.swing.JSpinner();
        C500_2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Do = new javax.swing.JButton();
        Retiros = new javax.swing.JDialog();
        CuentaP = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        C100 = new javax.swing.JSpinner();
        C500 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Total1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Do1 = new javax.swing.JButton();
        Log = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trans = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Principal = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        Salir1 = new javax.swing.JButton();
        Salir2 = new javax.swing.JButton();
        Salir4 = new javax.swing.JButton();
        Maintenance = new javax.swing.JDialog();
        Cuentas2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        c1003 = new javax.swing.JSpinner();
        c5003 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Total2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Do2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        EstadoCuenta = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        CuentasPropias = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        CreateUser = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        pnombre = new javax.swing.JTextField();
        snombre = new javax.swing.JTextField();
        papellido = new javax.swing.JTextField();
        sapellido = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        ayear = new com.toedter.calendar.JYearChooser();
        byear = new com.toedter.calendar.JYearChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        CreateATM = new javax.swing.JDialog();
        location = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        yearr = new com.toedter.calendar.JYearChooser();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        mant = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jt_userlogin = new javax.swing.JTextField();
        pw_pwlogin = new javax.swing.JPasswordField();
        Sucursal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LogIn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(157, 236, 217));

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton2.setText("Retiros");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton3.setText("Estado Cuenta");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton4.setText("Depositos");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton5.setText("Trasacciones");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 153));
        jButton6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButton6.setText("Nueva Cuenta");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 255, 153));
        Salir.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        Time.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout WhateverLayout = new javax.swing.GroupLayout(Whatever.getContentPane());
        Whatever.getContentPane().setLayout(WhateverLayout);
        WhateverLayout.setHorizontalGroup(
            WhateverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WhateverLayout.setVerticalGroup(
            WhateverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        buttonGroup1.add(CPropia);
        CPropia.setText("Cuenta Propia");
        CPropia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPropiaMouseClicked(evt);
            }
        });

        buttonGroup1.add(CAjena);
        CAjena.setText("Cuenta Ajena");
        CAjena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAjenaMouseClicked(evt);
            }
        });

        Cuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione una Cuenta --" }));

        jLabel4.setText("Seleccionar Cuenta");

        jLabel5.setText("¿A qué tipo de cuenta desea hacer un deposito?");

        C100_2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C100_2StateChanged(evt);
            }
        });

        C500_2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C500_2StateChanged(evt);
            }
        });

        jLabel6.setText("Cantidad de 100s");

        jLabel7.setText("Cantidad de 500s");

        jLabel8.setText("TOTAL A DEPOSITAR");

        Do.setText("Realizar Transacción");
        Do.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DepositosLayout = new javax.swing.GroupLayout(Depositos.getContentPane());
        Depositos.getContentPane().setLayout(DepositosLayout);
        DepositosLayout.setHorizontalGroup(
            DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositosLayout.createSequentialGroup()
                .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(DepositosLayout.createSequentialGroup()
                                .addComponent(CPropia)
                                .addGap(18, 18, 18)
                                .addComponent(CAjena))
                            .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DepositosLayout.createSequentialGroup()
                                    .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(C100_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(C500_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addGroup(DepositosLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(DepositosLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Do)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        DepositosLayout.setVerticalGroup(
            DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CAjena)
                    .addComponent(CPropia))
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C100_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C500_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(41, 41, 41)
                .addComponent(Do)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        CuentaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione una Cuenta --" }));

        jLabel9.setText("Seleccionar ATM");

        C100.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C100StateChanged(evt);
            }
        });

        C500.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C500StateChanged(evt);
            }
        });

        jLabel11.setText("Cantidad de 100s");

        jLabel12.setText("Cantidad de 500s");

        jLabel13.setText("TOTAL A RETIRAR");

        Do1.setText("Realizar Retiro");
        Do1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Do1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RetirosLayout = new javax.swing.GroupLayout(Retiros.getContentPane());
        Retiros.getContentPane().setLayout(RetirosLayout);
        RetirosLayout.setHorizontalGroup(
            RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetirosLayout.createSequentialGroup()
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RetirosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(RetirosLayout.createSequentialGroup()
                                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(C100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C500, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CuentaP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RetirosLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Total1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RetirosLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Do1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        RetirosLayout.setVerticalGroup(
            RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetirosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CuentaP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Total1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Do1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Trans.setEditable(false);
        Trans.setColumns(20);
        Trans.setRows(5);
        jScrollPane1.setViewportView(Trans);

        jLabel10.setText("Transacciones");

        javax.swing.GroupLayout LogLayout = new javax.swing.GroupLayout(Log.getContentPane());
        Log.getContentPane().setLayout(LogLayout);
        LogLayout.setHorizontalGroup(
            LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(172, 172, 172))
        );
        LogLayout.setVerticalGroup(
            LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Salir1.setText("Nuevo Usuario");
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
        });

        Salir2.setText("Salir");
        Salir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir2MouseClicked(evt);
            }
        });
        Salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir2ActionPerformed(evt);
            }
        });

        Salir4.setText("Nuevo ATM");
        Salir4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(Salir4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Salir2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal.getContentPane());
        Principal.getContentPane().setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Cuentas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar ATM --" }));

        jLabel14.setText("Seleccionar ATM");

        c1003.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                c1003StateChanged(evt);
            }
        });
        c1003.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1003MouseClicked(evt);
            }
        });

        c5003.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                c5003StateChanged(evt);
            }
        });
        c5003.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c5003MouseClicked(evt);
            }
        });

        jLabel15.setText("Cantidad de 100s");

        jLabel16.setText("Cantidad de 500s");

        jLabel17.setText("TOTAL A INGRESAR");

        Do2.setText("Realizar Mantenimiento");
        Do2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Do2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MaintenanceLayout = new javax.swing.GroupLayout(Maintenance.getContentPane());
        Maintenance.getContentPane().setLayout(MaintenanceLayout);
        MaintenanceLayout.setHorizontalGroup(
            MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintenanceLayout.createSequentialGroup()
                .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaintenanceLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(MaintenanceLayout.createSequentialGroup()
                                .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(c1003, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c5003, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cuentas2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MaintenanceLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Total2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MaintenanceLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Do2)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        MaintenanceLayout.setVerticalGroup(
            MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintenanceLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cuentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1003, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5003, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Total2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Do2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        CuentasPropias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione una Cuenta --" }));

        jButton12.setText("Revisar Estado de Cuenta");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel18.setText("Seleccione una Cuenta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(CuentasPropias, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton12)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(CuentasPropias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout EstadoCuentaLayout = new javax.swing.GroupLayout(EstadoCuenta.getContentPane());
        EstadoCuenta.getContentPane().setLayout(EstadoCuentaLayout);
        EstadoCuentaLayout.setHorizontalGroup(
            EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EstadoCuentaLayout.setVerticalGroup(
            EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel19.setText("Año de Afiliación");

        jLabel20.setText("Año de Nacimiento");

        jLabel21.setText("Primer Nombre");

        jLabel22.setText("Segundo Nombre");

        jLabel23.setText("Primer Apellido");

        jLabel24.setText("Segundo Apellido");

        jLabel25.setText("Usuario");

        jLabel26.setText("Contaseña");

        jButton7.setText("Guardar Usuario");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(papellido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(snombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(byear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ayear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addGap(87, 87, 87)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(papellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(byear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ayear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CreateUserLayout = new javax.swing.GroupLayout(CreateUser.getContentPane());
        CreateUser.getContentPane().setLayout(CreateUserLayout);
        CreateUserLayout.setHorizontalGroup(
            CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CreateUserLayout.setVerticalGroup(
            CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel27.setText("Ubicación");

        jLabel28.setText("ID");

        jLabel29.setText("Año de Fabricación");

        mant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "Mensual", "Anual", "Semanal" }));

        jLabel30.setText("Mantenimiento");

        jButton8.setText("Guarda ATM");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CreateATMLayout = new javax.swing.GroupLayout(CreateATM.getContentPane());
        CreateATM.getContentPane().setLayout(CreateATMLayout);
        CreateATMLayout.setHorizontalGroup(
            CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateATMLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateATMLayout.createSequentialGroup()
                        .addGroup(CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addGroup(CreateATMLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(34, 34, 34)))
                        .addGap(36, 36, 36)
                        .addGroup(CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(id))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CreateATMLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mant, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(CreateATMLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CreateATMLayout.setVerticalGroup(
            CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateATMLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CreateATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jButton8)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jt_userlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_userloginMouseClicked(evt);
            }
        });
        jt_userlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_userloginActionPerformed(evt);
            }
        });

        Sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione una Sucursal --" }));
        Sucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SucursalMouseClicked(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setText("Surcursal");

        LogIn.setText("Ingresar");
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Sucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pw_pwlogin)
                    .addComponent(jt_userlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_userlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pw_pwlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_userloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_userloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_userloginActionPerformed

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
        String un = jt_userlogin.getText();
        String pw = pw_pwlogin.getText();
        System.out.println(Users);
        for (Usuarios U : Users) {
            if (U.getUN().equalsIgnoreCase(un) && U.getPW().equals(pw)) {
                USER = U;
                A = (ATM) Sucursal.getSelectedItem();
                JOptionPane.showMessageDialog(this, "¡Bievenido a nuestra sucursal ATM, " + USER.getPNombre() + " " + USER.getPApellido());
                if (USER instanceof Cliente && (!(Sucursal.getSelectedItem().toString().equals("Sucursal Principal")))) {
                    Whatever.pack();
                    Whatever.setLocationRelativeTo(null);
                    Whatever.setVisible(true);
                    this.setVisible(false);
                } else if (USER instanceof Cliente && Sucursal.getSelectedItem().toString().equals("Sucursal Principal")) {
                    Principal.pack();
                    Principal.setLocationRelativeTo(null);
                    Principal.setVisible(true);
                    this.setVisible(false);
                } else if (USER instanceof Mantenimiento) {
                    Maintenance.pack();
                    Maintenance.setLocationRelativeTo(null);
                    Maintenance.setVisible(true);
                    this.setVisible(false);
                    DefaultComboBoxModel m = (DefaultComboBoxModel) Cuentas2.getModel();
                    for (ATM a : ((Mantenimiento) USER).getAsignados()) {
                        m.addElement(a);
                    }
                }
                break;
            } else if (U.getUN().equalsIgnoreCase(un) && (!U.getPW().equals(pw))) {
                pw_pwlogin.setBackground(Color.pink);
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta.\nInténtelo de nuevo.");
                pw_pwlogin.setText("");
                break;
            } else if (Users.indexOf(U) == Users.size() - 1 && (!U.getUN().equals(un))) {
                JOptionPane.showMessageDialog(this, "El usuario ingresado no existe.\nInténtelo de nuevo con otro usuario o contacte el administrador del equipo.");
                jt_userlogin.setText("");
                pw_pwlogin.setText("");
            }
        }

    }//GEN-LAST:event_LogInMouseClicked

    private void jt_userloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_userloginMouseClicked

    }//GEN-LAST:event_jt_userloginMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultComboBoxModel m = (DefaultComboBoxModel) CuentaP.getModel();
        for (Cuenta C : ((Cliente) USER).getCuentas()) {
            m.addElement(C);
        }
        CuentaP.setModel(m);
        Retiros.pack();
        Retiros.setLocationRelativeTo(null);
        Retiros.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void C100StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C100StateChanged
        int tot = (int) C100.getValue() * 100 + (int) C500.getValue() * 500;
        Total1.setText(String.valueOf(tot));
    }//GEN-LAST:event_C100StateChanged

    private void C500StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C500StateChanged
        int tot = (int) C100.getValue() * 100 + (int) C500.getValue() * 500;
        Total1.setText(String.valueOf(tot));
    }//GEN-LAST:event_C500StateChanged

    private void Do1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Do1MouseClicked
        double SaldoA = ((Cuenta) CuentaP.getSelectedItem()).getSaldo();
        int Ret = Integer.parseInt(Total1.getText());
        if (Ret > SaldoA) {
            JOptionPane.showMessageDialog(null, "No tiene dinero suficiente para realizar el retiro.");
        } else {
            ((Cuenta) CuentaP.getSelectedItem()).setSaldo(SaldoA - Ret);
            JOptionPane.showMessageDialog(null, "¡Retiro realizado exitósamente!\n Su saldo actual es de HNL." + ((Cuenta) CuentaP.getSelectedItem()).getSaldo());
            ((Cliente) USER).getLog().add(new Logs(USER.getUN(), "Retiro de HNL." + Ret, new Date()));
            A.setSaldoTotal(A.getSaldoTotal() - Ret);
        }
        Retiros.setVisible(false);
        CuentaP.setSelectedIndex(0);
        Total1.setText("");
        C100.setValue(0);
        C500.setValue(0);
        BinaryManager BM = new BinaryManager("./User Information.aj");
        BM.cargarArchivo();
        for (Object user1 : BM.getUsers()) {
            if (((Cliente) user1).getUN().equals(USER.getUN())) {
                for (Cuenta c : ((Cliente) user1).getCuentas()) {
                    if (c.equals(((Cuenta) CuentaP.getSelectedItem()))) {
                        c.setSaldo(SaldoA - Ret);
                    }
                }

            }
        }
        BM.escribirArchivo();
        ATMManager AM = new ATMManager("./ATM Information.aj");
        AM.cargarArchivo();
        for (Object user1 : AM.getATMS()) {
            if (((ATM) user1).equals(A)) {
                ((ATM) user1).setSaldoTotal(A.getSaldoTotal() - Ret);
            }

        }
        AM.escribirArchivo();
    }//GEN-LAST:event_Do1MouseClicked

    private void C100_2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C100_2StateChanged
        int tot = (int) C100_2.getValue() * 100 + (int) C500_2.getValue() * 500;
        Total.setText(String.valueOf(tot));
    }//GEN-LAST:event_C100_2StateChanged

    private void CPropiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPropiaMouseClicked
        DefaultComboBoxModel m = (DefaultComboBoxModel) Cuentas.getModel();
        if (CPropia.isSelected()) {
            for (Cuenta C : ((Cliente) USER).getCuentas()) {
                m.addElement(C);
            }
            Cuentas.setModel(m);
        }
    }//GEN-LAST:event_CPropiaMouseClicked

    private void C500_2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C500_2StateChanged
        int tot = (int) C100_2.getValue() * 100 + (int) C500_2.getValue() * 500;
        Total.setText(String.valueOf(tot));
    }//GEN-LAST:event_C500_2StateChanged

    private void CAjenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAjenaMouseClicked
        DefaultComboBoxModel m = (DefaultComboBoxModel) Cuentas.getModel();
        for (Usuarios User : Users) {
            Cliente C = (Cliente) User;
            if (C instanceof Cliente) {
                for (Cuenta cuenta : C.getCuentas()) {
                    m.addElement(cuenta);
                }
            }
        }
        Cuentas.setModel(m);
    }//GEN-LAST:event_CAjenaMouseClicked

    private void DoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoMouseClicked
        double SaldoA = ((Cuenta) Cuentas.getSelectedItem()).getSaldo();
        int Dep = Integer.parseInt(Total.getText());
        ((Cuenta) Cuentas.getSelectedItem()).setSaldo(SaldoA + Dep);
        JOptionPane.showMessageDialog(null, "¡Deposito realizado exitósamente!\n  El saldo actual es de HNL." + ((Cuenta) Cuentas.getSelectedItem()).getSaldo());
        ((Cliente) USER).getLog().add(new Logs(USER.getUN(), "Deposito a cuenta " + ((Cuenta) Cuentas.getSelectedItem()).toString() + " de HNL." + Dep, new Date()));
        BinaryManager BM = new BinaryManager("./User Information.aj");
        BM.cargarArchivo();
        for (Object user1 : BM.getUsers()) {
            if (((Cliente) user1).getUN().equals(USER.getUN())) {
                for (Cuenta c : ((Cliente) user1).getCuentas()) {
                    if (c.equals(((Cuenta) Cuentas.getSelectedItem()))) {
                        c.setSaldo(SaldoA + Dep);
                    }
                }

            }
        }
        BM.escribirArchivo();
        ATMManager AM = new ATMManager("./ATM Information.aj");
        AM.cargarArchivo();
        for (Object user1 : AM.getATMS()) {
            if (((ATM) user1).equals(A)) {
                ((ATM) user1).setSaldoTotal(A.getSaldoTotal() + Dep);
            }

        }
        AM.escribirArchivo();
        Cuentas.setSelectedIndex(0);
        Total.setText("");
        C100_2.setValue(0);
        C500_2.setValue(0);
    }//GEN-LAST:event_DoMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Random r = new Random();
        int CID = 100000000 + r.nextInt(999999999);
        Cuenta c = new Cuenta(CID, 0, USER.getUN());
        ((Cliente) USER).getCuentas().add(c);
        BinaryManager BM = new BinaryManager("./User Information.aj");
        BM.cargarArchivo();
        System.out.println(BM.getUsers());
        for (Usuarios user1 : BM.getUsers()) {
            if (((Cliente) user1).getUN().equals(USER.getUN())) {
                ((Cliente) user1).addCuenta(c);

            }
            break;
        }
        BM.escribirArchivo();
        JOptionPane.showMessageDialog(null, "¡Cuenta realizada exitósamente.\n El número de su nueva cuenta es: " + CID);

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        DefaultComboBoxModel m = (DefaultComboBoxModel) CuentasPropias.getModel();
        for (Cuenta C : ((Cliente) USER).getCuentas()) {
            m.addElement(C);
        }
        CuentasPropias.setModel(m);
        EstadoCuenta.pack();
        EstadoCuenta.setLocationRelativeTo(null);
        EstadoCuenta.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        Cuenta T = ((Cuenta) CuentasPropias.getSelectedItem());
        double t = T.getSaldo();
        JOptionPane.showMessageDialog(null, "Su saldo actual es de HNL." + t);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Log.pack();
        Log.setLocationRelativeTo(null);
        Log.setVisible(true);
        Trans.setText("");
        String temp = "";
        for (Logs logs : ((Cliente) USER).getLog()) {
            temp += logs.toString() + "\n";
        }
        Trans.setText(temp);
        BinaryManager BM = new BinaryManager("./User Information.aj");
        for (Usuarios user1 : BM.getUsers()) {
            if (((Cliente) user1).getUN().equals(USER.getUN())) {
                ((Cliente) user1).setLog(((Cliente) USER).getLog());
            }
            break;
        }
        BM.escribirArchivo();
    }//GEN-LAST:event_jButton5MouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        this.setVisible(true);
        Whatever.setVisible(false);
    }//GEN-LAST:event_SalirMouseClicked

    private void Salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir2ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        Users.add(new Usuarios(user.getText(), pnombre.getText(), snombre.getText(), papellido.getText(), sapellido.getText(), pw.getText(), String.valueOf(byear.getValue()), String.valueOf(ayear.getValue()), new ArrayList()));
        JOptionPane.showMessageDialog(null, "¡Usuario creado exitósamente!");
        user.setText("");
        snombre.setText("");
        papellido.setText("");
        sapellido.setText("");
        pw.setText("");
        byear.setValue(2018);
        ayear.setValue(2018);
        BinaryManager BM = new BinaryManager("./User Information.aj");
        BM.cargarArchivo();
        BM.getUsers().add(new Usuarios(user.getText(), pnombre.getText(), snombre.getText(), papellido.getText(), sapellido.getText(), pw.getText(), String.valueOf(byear.getValue()), String.valueOf(ayear.getValue()), new ArrayList()));
        BM.escribirArchivo();

    }//GEN-LAST:event_jButton7MouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        ATMs.add(new ATM(location.getText(), Integer.parseInt(id.getText()), yearr.getValue(), mant.getSelectedItem().toString()));
        JOptionPane.showMessageDialog(null, "¡ATM creado exitósamente!");
        location.setText("");
        id.setText("");
        yearr.setValue(2018);
        mant.setSelectedIndex(0);

        ATMManager AM = new ATMManager("./ATM Information.aj");
        AM.cargarArchivo();
        AM.getATMS().add(new ATM(location.getText(), Integer.parseInt(id.getText()), yearr.getValue(), mant.getSelectedItem().toString()));
        AM.escribirArchivo();
    }//GEN-LAST:event_jButton8MouseClicked

    private void Do2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Do2MouseClicked
        ((ATM) Cuentas2.getSelectedItem()).setSaldoTotal(((ATM) Cuentas2.getSelectedItem()).getSaldoTotal() + Integer.parseInt(Total2.getText()));
        JOptionPane.showMessageDialog(null, "¡Mantenimiento realizado exitósamente");
        ATMManager AM = new ATMManager("./ATM Information.aj");
        AM.cargarArchivo();
        for (Object user1 : AM.getATMS()) {
            if (((ATM) user1).equals(((ATM) Cuentas2.getSelectedItem()))) {
                ((ATM) user1).setSaldoTotal(((ATM) Cuentas2.getSelectedItem()).getSaldoTotal() + Integer.parseInt(Total2.getText()));
            }
        }
        AM.escribirArchivo();
    }//GEN-LAST:event_Do2MouseClicked

    private void c1003MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1003MouseClicked
        int tot = (int) c1003.getValue() * 100 + (int) c5003.getValue() * 500;
        Total2.setText(String.valueOf(tot));
    }//GEN-LAST:event_c1003MouseClicked

    private void c5003MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5003MouseClicked
        int tot = (int) c1003.getValue() * 100 + (int) c5003.getValue() * 500;
        Total2.setText(String.valueOf(tot));
    }//GEN-LAST:event_c5003MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        DefaultComboBoxModel m = (DefaultComboBoxModel) Cuentas.getModel();
        for (Cuenta C : ((Cliente) USER).getCuentas()) {
            m.addElement(C);
        }
        Cuentas.setModel(m);

        Depositos.pack();
        Depositos.setLocationRelativeTo(null);
        Depositos.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void SucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SucursalMouseClicked
        if (evt.getClickCount() <= 1) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) Sucursal.getModel();
            for (Object ATM : ATMs) {
                m.addElement(ATM);
            }
            Sucursal.setModel(m);
        }
    }//GEN-LAST:event_SucursalMouseClicked

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
        CreateUser.pack();
        CreateUser.setLocationRelativeTo(null);
        CreateUser.setVisible(true);
    }//GEN-LAST:event_Salir1MouseClicked

    private void Salir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir4MouseClicked
        CreateATM.pack();
        CreateATM.setLocationRelativeTo(null);
        CreateATM.setVisible(true);
    }//GEN-LAST:event_Salir4MouseClicked

    private void Salir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir2MouseClicked
    System.exit(0);
    }//GEN-LAST:event_Salir2MouseClicked

    private void c1003StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_c1003StateChanged
       int tot = (int) c1003.getValue() * 100 + (int) c5003.getValue() * 500;
        Total2.setText(String.valueOf(tot));
    }//GEN-LAST:event_c1003StateChanged

    private void c5003StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_c5003StateChanged
       int tot = (int) c1003.getValue() * 100 + (int) c5003.getValue() * 500;
        Total2.setText(String.valueOf(tot));
    }//GEN-LAST:event_c5003StateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    public static void main(String args[]) {
        /* Usuarios A = new Cliente(new ArrayList(), "andreaj", "Andrea", "José", "Mendoza", "Castañeda", "andrea123", "1999", "2018", new ArrayList());
        Usuarios B = new Mantenimiento(new ArrayList(), "diegom", "Diego", "", "Mendoza", "", "dieog123", "1997", "2018", new ArrayList());
        ATM A1 = new ATM("Mall Multiplaza", 123, 2017, "Mensual");
        ATM A2 = new ATM("Sucursal Principal", 001, 2005, "Semanal");
        ((Mantenimiento) B).addATMs(A1);
        ((Mantenimiento) B).addATMs(A2);*/
        System.out.println("Cuenta: andreaj \n PW: andreaj123");
        System.out.println("Cuenta Matenimiento: diegom \n PW: dieog123");
        BinaryManager BM = new BinaryManager("./User Information.aj");
        BM.cargarArchivo();
        //    BM.getUsers().add(A);
        //   BM.getUsers().add(B);
        Users = BM.getUsers();
        //     BM.escribirArchivo();
        System.out.println(Users);
        ATMManager AM = new ATMManager("./ATM Information.aj");
        AM.cargarArchivo();
        //     AM.getATMS().add(A1);
        //    AM.getATMS().add(A2);
        ATMs = AM.getATMS();
        //    AM.escribirArchivo();
        System.out.println(ATMs);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner C100;
    private javax.swing.JSpinner C100_2;
    private javax.swing.JSpinner C500;
    private javax.swing.JSpinner C500_2;
    private javax.swing.JRadioButton CAjena;
    private javax.swing.JRadioButton CPropia;
    private javax.swing.JDialog CreateATM;
    private javax.swing.JDialog CreateUser;
    private javax.swing.JComboBox<String> CuentaP;
    private javax.swing.JComboBox<String> Cuentas;
    private javax.swing.JComboBox<String> Cuentas2;
    private javax.swing.JComboBox<String> CuentasPropias;
    private javax.swing.JDialog Depositos;
    private javax.swing.JButton Do;
    private javax.swing.JButton Do1;
    private javax.swing.JButton Do2;
    private javax.swing.JDialog EstadoCuenta;
    private javax.swing.JDialog Log;
    private javax.swing.JButton LogIn;
    private javax.swing.JDialog Maintenance;
    private javax.swing.JDialog Principal;
    private javax.swing.JDialog Retiros;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Salir1;
    private javax.swing.JButton Salir2;
    private javax.swing.JButton Salir4;
    private javax.swing.JComboBox<String> Sucursal;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField Total1;
    private javax.swing.JTextField Total2;
    private javax.swing.JTextArea Trans;
    private javax.swing.JDialog Whatever;
    private com.toedter.calendar.JYearChooser ayear;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JYearChooser byear;
    private javax.swing.JSpinner c1003;
    private javax.swing.JSpinner c5003;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt_userlogin;
    private javax.swing.JTextField location;
    private javax.swing.JComboBox<String> mant;
    private javax.swing.JTextField papellido;
    private javax.swing.JTextField pnombre;
    private javax.swing.JPasswordField pw;
    private javax.swing.JPasswordField pw_pwlogin;
    private javax.swing.JTextField sapellido;
    private javax.swing.JTextField snombre;
    private javax.swing.JTextField user;
    private com.toedter.calendar.JYearChooser yearr;
    // End of variables declaration//GEN-END:variables
static ArrayList<Usuarios> Users;
    static ArrayList<ATM> ATMs;
    ArrayList<Integer> Accs;
    Usuarios USER;
    ATM A;

}
